server:
  port: 10900
  error:
    include-message: always

spring:
  application:
    name: mini-cactpot-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/mini-cactpot-db?authSource=admin

application:
  security:
    allowed-origins:
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allow-credentials: true
    allowed-headers:
      - Content-Type
    exposed-headers:
      - Content-Type
  cleanup:
    aggregate-cleanup-cron: 0 0 * ? * *
    cutoff-hours: 24

mini-cactpot:
  winnings-map:
    6: 10000
    7: 36
    8: 720
    9: 360
    10: 80
    11: 252
    12: 108
    13: 72
    14: 54
    15: 180
    16: 72
    17: 180
    18: 119
    19: 36
    20: 306
    21: 1080
    22: 144
    23: 1800
    24: 3600